# Generated by Django 4.2 on 2024-07-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://imgs.search.brave.com/hX5zILJ8FRbfpcVsB1brwF7Ih4WshICCHo514X0oyK8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS50ZW5vci5jb20v/WEszN0dmYlYwZzhB/QUFBai9sb2FkaW5n/LWNhcmdhbmRvLmdp/Zg.gif', max_length=500),
        ),
    ]
