# Generated by Django 4.2 on 2024-07-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://imgs.search.brave.com/0IOQ36WzS8XUXevrHw22EYgKB9yC8U_fq8_lE0Et65s/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTM1/Nzg4MDQ4Ny92ZWN0/b3IvbG9hZGluZy5q/cGc_cz02MTJ4NjEy/Jnc9MCZrPTIwJmM9/WHhsNmpSeTB0b25E/M0NRLWRzSXdNb2R4/b3VhS0dJcjRvYkFG/MlphMURnST0', max_length=500),
        ),
    ]
